name: benchmark
description: Signals benchmark to other state libraries
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  benchmarking: ^0.6.1
  signals:
    path: ../packages/signals
  solidart: ^1.5.4
  state_beacon: ^0.45.0
  styled_text: ^8.1.0
  flutter_markdown: ^0.6.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

