name: signals_flutter
description: Flutter extensions for signals_core
version: 4.5.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://rodydavis.github.io/signals.dart
documentation: https://rodydavis.github.io/signals.dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signals_core: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - signal
  - reactive
  - state
  - signals
  - rx

scripts:
  coverage:
    - flutter test --coverage
    - genhtml coverage/lcov.info -o coverage/html
    - open coverage/html/index.html
