name: signals
sdkPath: .fvm/flutter_sdk

packages:
  - examples/*
  - packages/*

scripts:
  examples:
    exec: dart scripts/examples.dart
  analyze:
    exec: dart analyze .
  flutter:test:
    exec: flutter test
    packageFilters:
      flutter: true
      scope: "*signals_flutter*"
  dart:test:
    exec: dart test
    packageFilters:
      flutter: false
      scope: "*signals_core*"
  test:
    exec: melos run dart:test --no-select && melos run flutter:test --no-select
  
  coverage:dart:
    exec: dart pub global run coverage:test_with_coverage
    packageFilters:
      flutter: false
      scope: "*signals_core*"
  coverage:flutter:
    exec: flutter test --coverage
    packageFilters:
      flutter: true
      scope: "*signals_flutter*"
  coverage:report:
    exec: genhtml coverage/lcov.info -o coverage/html

  combine_coverage:
    run: melos exec -- "\$MELOS_ROOT_PATH/scripts/combine_coverage.sh"

command:
  version:
    hooks:
      preCommit: |
        # Make changes to the version commit here.
        # You need to stage changes that you make yourself.
  