name: signals
sdkPath: .fvm/flutter_sdk

packages:
  - examples/*
  - packages/*

scripts:
  examples:
    exec: dart scripts/examples.dart
  analyze:
    exec: dart analyze .
  flutter:test:
    exec: flutter test
    packageFilters:
      flutter: true
      scope: "*signals_flutter*"
  dart:test:
    exec: dart test
    packageFilters:
      flutter: false
      scope: "*signals_core*"
  test:
    exec: melos run dart:test --no-select && melos run flutter:test --no-select

command:
  version:
    hooks:
      preCommit: |
        # Make changes to the version commit here.
        # You need to stage changes that you make yourself.
