name: example
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  signals:
    path: ../..

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
