name: node_based_editor
description: Logic is in the nodes
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dart_mappable: ^4.2.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  mustache_template: ^2.0.0
  recase: ^4.1.0
  shared_preferences: ^2.2.2
  signals: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.0
  yaml: ^3.1.2

flutter:
  uses-material-design: true

scripts:
  build: dart pub run build_runner build
  nodes:
    - dart run -r scripts/nodes.dart
    - dart pub run build_runner build
    - dart format .
