name: signals_dart_examples
description: Demonstrates Signals
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

dependencies:
  signals:
    path: ../../packages/signals

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
