name: signals_dart_examples
description: Pure dart examples using signals
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

dependencies:
  collection:
  signals:
    path: ../../packages/signals
  sqlite_async: ^0.5.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
