name: signals_core
description: Reactivity made simple. Do more by doing less.
version: 4.4.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://rodydavis.github.io/signals.dart
documentation: https://rodydavis.github.io/signals.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - signal
  - reactive
  - state
  - signals
  - rx

scripts:
  coverage:
    - dart pub global run coverage:test_with_coverage
    - genhtml coverage/lcov.info -o coverage/html
    - open coverage/html/index.html