name: signals_macro
description: Express Signals as macro
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-99.0.dev

# Add regular dependencies here.
dependencies:
  signals_core: 

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  _fe_analyzer_shared: any
  frontend_server: any

dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: main
  _js_interop_checks:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_js_interop_checks
      ref: main
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analyzer
      ref: main
  build_integration:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/build_integration
      ref: main
  compiler:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/compiler
      ref: main
  dart2js_info:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/dart2js_info
      ref: main
  dart2wasm:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/dart2wasm
      ref: main
  dev_compiler:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/dev_compiler
      ref: main
  front_end:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/front_end
      ref: main
  frontend_server:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/frontend_server
      ref: main
  js_ast:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js_ast
      ref: main
  js_runtime:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js_runtime
      ref: main
  js_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js_shared
      ref: main
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/kernel
      ref: main
  mmap:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/mmap
      ref: main
  vm:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/vm
      ref: main
  wasm_builder:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/wasm_builder
      ref: main
