name: preact_signals
description: Signal, Computed and Effect built with dart
version: 0.0.2
repository: https://github.com/rodydavis/preact_signals.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  test: ^1.24.3
