name: drift_example
description: SQLite via drift and signals
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  go_router: ^13.1.0
  signals:
    path: ../../packages/signals
  flutter_colorpicker: ^1.0.3
  file_picker: ^6.1.1
  sqlite3: ^2.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
