name: signals_devtools_extension
description: Signals DevTools extension.
publish_to: "none"
version: 1.0.2
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  devtools_extensions: ^0.0.10
  devtools_app_shared: ^0.0.6
  force_directed_graphview: ^0.6.0
  faker: ^2.1.0
  signals:
    path: ../signals

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
