name: signals
description: "signal, computed and effect built with dart and extensions for flutter"
repository: https://github.com/rodydavis/signals.dart
homepage: https://rodydavis.github.io/signals.dart/
version: 1.3.4

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
