name: Tests

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.5.0

      - name: Install melos
        run: dart pub global activate melos

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"

      - name: Install dependencies
        run: melos exec --no-private flutter pub get
      
      - name: Analyze packages
        run: melos run analyze

      - name: Test packages
        run: melos run test
